source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MySwiftExtension_Example', :exclusive => true do
  pod "MySwiftExtension", :path => "../"
end

target 'MySwiftExtension_Tests', :exclusive => true do
  pod "MySwiftExtension", :path => "../"

  
end
